Repository Sanket1308/Simple-Calculator, pull requests merged in 2022-10, with the labels that each got.

#17 :heavy_check_mark: Added Poppins font and Added Github link
  css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#35 Update style.css
  css/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#37 Update style.css
  css/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#41 Create a logo
  README.md
  css/style.css
  img/logo.svg
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#49 Themes added
  css/style.css
  img/dark.jpg
  img/light.jpg
  img/moon.png
  img/sun.png
  index.html
  js/script.js
Labels: hacktoberfest, hacktoberfest-accepted

#56 mobile-fix
  css/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#61 Added favicon.ico to the website
  img/favicon.ico
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#66 Added sound on click (solves #62), improved styling of calculator
  Audio/calculatorclick.mp3
  css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#77 added mute button on upper right corner
  css/style.css
  index.html
  js/script.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
